export const TYPES = {
	PrismaClient: Symbol.for("PrismaClient"),
	InstitucionRepository: Symbol.for("InstitucionRepository"),
	InstitucionService: Symbol.for("InstitucionService"),
	MallaCurricularRepository: Symbol.for("MallaCurricularRepository"),
	MallaCurricularService: Symbol.for("MallaCurricularService"),
	AsignaturaRepository: Symbol.for("AsignaturaRepository"),
	AsignaturaService: Symbol.for("AsignaturaService"),
	CursoRepository: Symbol.for("CursoRepository"),
	CursoService: Symbol.for("CursoService"),
	CompetenciaRepository: Symbol.for("CompetenciaRepository"),
	CompetenciaService: Symbol.for("CompetenciaService"),
	AsignaturaEnMallaRepository: Symbol.for("AsignaturaEnMallaRepository"),
	AsignaturaEnMallaService: Symbol.for("AsignaturaEnMallaService"),
	EjeFormativoRepository: Symbol.for("EjeFormativoRepository"),
	EjeFormativoService: Symbol.for("EjeFormativoService"),
	CampoFormacionRepository: Symbol.for("CampoFormacionRepository"),
	CampoFormacionService: Symbol.for("CampoFormacionService"),
	AreaConocimientoRepository: Symbol.for("AreaConocimientoRepository"),
	AreaConocimientoService: Symbol.for("AreaConocimientoService"),
	LugarEjecucionRepository: Symbol.for("LugarEjecucionRepository"),
} as const;
